### ISSUE TITLE
Frame drops when recieving an item in 5-S

### ISSUE THREAD

**Issue by NintenGunner** [TRPG0/ArchipelagoULTRAKILL#10]
When playing with 4 other players, whenever I was playing 5-S and received an item from one of them collecting something (one of these was the Attractor Nailgun, for example), my frames started suddenly getting bad. Like, really bad. For reference, I enabled the "give items for catching fish" setting, although I shall be uploading the yaml file for you to look at.
[NintenGunner.yaml (albeit as a .txt file because GitHub doesn't allow .yaml)](https://github.com/TRPG0/ArchipelagoULTRAKILL/files/13930425/NintenGunner.txt)

I'm not sure if you are aware of this bug as it is, but I'll be reporting it here for the sake of it.

_Originally posted by @NintenGunner in https://github.com/TRPG0/ArchipelagoULTRAKILL/discussions/9_

**Comment by TRPG0** [comment]
Fixed in 2.0.0
