### ISSUE TITLE
Not receiving items that the server is giving

### ISSUE THREAD

**Issue by i-eye** [TRPG0/ArchipelagoULTRAKILL#11]
On my first launch, I received items/stages, got a nice visual on screen. But I launched the game a second time, connected to the same server and used the same save slot, but every time I interacted with a secret, V2 boss drop, I received nothing. The server sent a message saying I received the item, but I didn't receive the item in-game. I tried generating a new game and I still got the same problem.

Another thing is I put the music randomizer on, and it still seems to work.

**Comment by TRPG0** [comment]
The new update that just got released seems to have broken some things in Archipelago. I'm working on fixing them right now
