### ISSUE TITLE
My game crashed when i clicked settings

### ISSUE THREAD

**Issue by KKaydoom** [TRPG0/ArchipelagoULTRAKILL#14]
![image](https://github.com/TRPG0/ArchipelagoULTRAKILL/assets/106564078/cf124e45-9275-4cd9-835a-7b00aa812172)

**Comment by KKaydoom** [comment]
this just happens all the time when im just playing the game

**Comment by TRPG0** [comment]
This error isn't very helpful unfortunately. Which version of PluginConfigurator are you using? If it crashes when you try to open the settings, it might be because PluginConfigurator is outdated.
