### ISSUE TITLE
Ship of Fools potential softlock

### ISSUE THREAD

**Issue by NintenGunner** [TRPG0/ArchipelagoULTRAKILL#17]
When running a run, the first level I obtained was Ship of Fools. Unfortunately, when I went to pick up the rocket launcher in order to trigger phase 2 of the level, it just... didn't happen. I could grab it, and it gave me the thing in it's place, but when I went backwards, phase 2 simply did not trigger. Even when I cheated in the freezeframe RL in order to hopefully trigger it via the game already detecting that I have the rocket launcher, it simply did not trigger. The hallway never turned upside down, and we could not progress with the run without cheating, because I could neither access the challenge, nor could I access the last two secrets of the level.

Here is the seed, given to me by the host. #YKNb23OhSvynUzCSKoGqNA
I am unaware of how seeds work, but I hope you might find this useful.
[ultrakill_again.yaml](https://github.com/TRPG0/ArchipelagoULTRAKILL/files/14814142/ultrakill_again.yaml.txt)
The yaml file I used for this run.

**Comment by TRPG0** [comment]
Hmm, I've never heard of this happening before. If this happens to you again it would be helpful if you could send your `LogOutput.log` file since it sounds like something has gone very wrong, and that would pretty much be my only way of figuring out what.

**Comment by NintenGunner** [comment]
I found the issue; it appears to be related to an alternate mod I installed earlier. I, honestly, completely forgot that I had installed it because it hadn't really affected anything else in the run. So, uh, whoops. Sorry.

Here's the [logoutput.log](https://github.com/TRPG0/ArchipelagoULTRAKILL/files/14818109/logoutput.txt) anyways.

**Comment by TRPG0** [comment]
Well that's still good to know either way. Though I'm curious which mod it was, since it seems like the file you tried to upload is empty

**Comment by NintenGunner** [comment]
That was an error. Don't know how the file uploaded empty. Here's the real thing.
[logoutput.txt](https://github.com/TRPG0/ArchipelagoULTRAKILL/files/14827159/logoutput.txt)
