### ISSUE TITLE
Connection Timed Out

### ISSUE THREAD

**Issue by OrionsExile** [TRPG0/ArchipelagoULTRAKILL#18]
Randomly when i try to connect to an AP Multiworld, it just doesn't work. I've seen it twice, it didn't work for multiple different worlds and then it did, even ones that it didn't previously. If what i said makes any sense, do you have a fix?

**Comment by TRPG0** [comment]
I'm not exactly sure what you're talking about, but it could be that rooms hosted on the Archipelago website shut down after being inactive for a while. When that happens all you have to do is refresh the page to get the room to open back up. Maybe that's it?

**Comment by spongedev1** [comment]
> it could be that rooms hosted on the Archipelago website shut down after being inactive for a while

this happens with local servers as well
