### ISSUE TITLE
[MOD REQUEST] A standalone mod that lets us customize what weapon drops give what weapon

### ISSUE THREAD

**Issue by UntotenTheo** [TRPG0/ArchipelagoULTRAKILL#20]
tldr
i think itd be funny if the mods feature of giving us random weapons was its own mod so we can do something like making the 0-1 Revolver give the Marksman, SM Shotgun gives Pump Charge, Nailgun gives Overheat, so on and so forth
uhh yeah thats it

**Comment by TRPG0** [comment]
You'd still be able to just buy all the other variations from the shop anyway so I don't really see the point

**Comment by UntotenTheo** [comment]
after playing through blue weapons only yeah this isnt worth the effort

disregard
