### ISSUE TITLE
Game disconnects me from Archipelago servers and crashes when i try to rejoin it

### ISSUE THREAD

**Issue by OrionsExile** [TRPG0/ArchipelagoULTRAKILL#22]

**Comment by OrionsExile** [comment]
If you'd like, we could talk more in depth about such and I may be able to show you if you'd like

**Comment by TRPG0** [comment]
The Archipelago website and servers are going through maintenance right now to fix critical bugs and memory leaks. You'll have to just wait until later, but if you're just playing singleplayer it's fairly easy to set up a solo server without having to go through a bunch of extra steps.

**Comment by OrionsExile** [comment]
that's the thing, I'm running a solo server singleplayer

**Comment by TRPG0** [comment]
Yes, but if it's being hosted on the Archipelago website, there will likely be issues now and until the maintenance is finished.

If you want to play solo you can run the server yourself by running `ArchipelagoServer.exe`, and then as long as the server and game are both running on the same computer, you can use `localhost` as the address to connect to it.

**Comment by OrionsExile** [comment]
oh, alright. Thank you
