### ISSUE TITLE
Newest version does not register as v1.1.4, and instead is called v1.1.3 and this then causes a connection timeout

### ISSUE THREAD

**Issue by Evilrymon** [TRPG0/ArchipelagoULTRAKILL#3]
They may or may not be related, but the file for v1.1.4 in-game shows up as v1.1.3 (The console also says that a new version is available) and if I try to connect to archipelago, it says it's connected, the server picks it up, and the game seems to see that. However, it just does nothing, and nothing actually works. The BepInEx console also says that it has timed out whilst connecting to archipelago.
The console is also full of messages saying "Null" or "Error in finding *number* Data" (numbers are usually 1-25 or 666, idk why) or "Secret Mission Status:0".
Connecting initially presents the issue "Command 'connect' failed. The given key was not present in the dictionary."

**Comment by TRPG0** [comment]
Could you try this again and then go to your install folder for ULTRAKILL, open the BepInEx folder, and post the `LogOutput.log` file?

**Comment by Evilrymon** [comment]
Sorry for such a long time between responses, turns out, the ULTRAKILL archipelago mod must've just been named wrong for some reason, and my actual archipelago installation was out of date.
