### ISSUE TITLE
Several different fish softlock the fishing minigame?

### ISSUE THREAD

**Issue by ashifolfi** [TRPG0/ArchipelagoULTRAKILL#7]
I just noticed while doing a run with fish rewards enabled that the PITR Fish, Bomb Fish, Metal Fish, and possibly others cause an object reference error when "caught" and won't fully get caught. blocking you from catching more fish, completing the minigame, and in the case of the bomb fish, gain access to a section of the fishing minigame

![image](https://github.com/TRPG0/ArchipelagoULTRAKILL/assets/29577987/e8f708ea-170c-4c92-9eef-bc47f6ed6923)
![image](https://github.com/TRPG0/ArchipelagoULTRAKILL/assets/29577987/3134409c-dede-4dc5-830d-60300df29650)

**Comment by TRPG0** [comment]
Can you send the spoiler log for this run?

**Comment by ashifolfi** [comment]
> Can you send the spoiler log for this run?

I am 90% sure all of the fish that were problematic attempted to give me weapons.
I sadly don't have the spoiler log for this run (by the time you made this comment I would have started another and deleted the files from this run) but I am very confident that those fish were weapon rewards.

I still have the log and checking it every fish I remember being unable to "catch" gave me a weapon according to the server.

![image](https://github.com/TRPG0/ArchipelagoULTRAKILL/assets/29577987/f57ed45f-bb7b-4855-ad4e-e545d98edb87)

pulled from the log here is what I was able to recall in terms of what had issues and what didn't

**Comment by TRPG0** [comment]
Fixed in 2.0.0
